In [1]:
import numpy as np

In [2]:
quality_score = np.arange(1.225, 1.8, 0.05)
quality_score

array([1.225, 1.275, 1.325, 1.375, 1.425, 1.475, 1.525, 1.575, 1.625,
       1.675, 1.725, 1.775])

In [6]:
import pandas as pd

df = pd.read_csv("problems/online_contract_edgeAI/model_perf.csv", header=None)
p = df.iloc[1:, 1:].astype(float).values
print(p)

[[ 1.5  6.  15.5 13.5 24.5 16.  16.   5.5  1.5  0.   0.   0. ]
 [ 0.   0.   2.   6.  17.5 19.5 18.5 22.  11.   2.5  1.   0. ]
 [ 0.   0.   0.5  3.   8.  17.  20.5 21.5 17.  10.   2.5  0. ]
 [ 0.   0.   1.   1.5 10.5 16.  21.5 21.  16.  10.5  2.   0. ]
 [ 0.   0.   0.   2.   6.5 16.5 18.5 23.5 17.5 12.   3.5  0. ]
 [ 0.   0.   0.   1.5  6.  12.5 18.5 20.5 20.  15.5  4.5  1. ]]


In [7]:
agent_setting = pd.DataFrame({
    **{f"p{j}": [row[j] for row in p] for j in range(12)}
})
agent_setting

p0   p1    p2    p3    p4    p5    p6    p7    p8    p9  p10  p11
0  1.5  6.0  15.5  13.5  24.5  16.0  16.0   5.5   1.5   0.0  0.0  0.0
1  0.0  0.0   2.0   6.0  17.5  19.5  18.5  22.0  11.0   2.5  1.0  0.0
2  0.0  0.0   0.5   3.0   8.0  17.0  20.5  21.5  17.0  10.0  2.5  0.0
3  0.0  0.0   1.0   1.5  10.5  16.0  21.5  21.0  16.0  10.5  2.0  0.0
4  0.0  0.0   0.0   2.0   6.5  16.5  18.5  23.5  17.5  12.0  3.5  0.0
5  0.0  0.0   0.0   1.5   6.0  12.5  18.5  20.5  20.0  15.5  4.5  1.0

In [8]:
a = np.array([12, 3, 45, 6])
c = np.max(a)
c

np.int64(45)

In [9]:
c = np.random.uniform(0, 1e-5, 12)
c

array([5.46896300e-06, 6.82137110e-06, 3.13180967e-07, 8.28381105e-06,
       7.29025304e-06, 7.52568696e-06, 3.52615451e-07, 2.29437765e-07,
       7.07370042e-06, 2.42979387e-06, 5.24359873e-06, 6.38070168e-06])

In [18]:
print(len(np.linspace(1.2, 1.8, 3)))

3


In [19]:
c[:2]

array([5.4689630e-06, 6.8213711e-06])